theme: jekyll-theme-hacker

navbar-col: "#000000"
navbar-text-col: "#000000"
navbar-border-col: "#000000"
page-col: "#000000"
text-col: "#000000"
link-col: "#000000"
hover-col: "#000000"
footer-col: "#EAEAEA"
footer-text-col: "#000000"
footer-link-col: "#000000"
footer-hover-col: "#000000"
